### PR TITLE
Add circomPath configuration parameter

### PR DESCRIPTION
**Pull request by numtel**
Hey Erhan,

Thanks for being receptive to that last PR. I've got another patch. This one is so that I can run multiple different versions of the circom executable inside AWS Lambda. I'm creating [Circuitscan, a circuit explorer](https://github.com/circuitscan/circuitscan) where people can verify their deployed verifier contracts.

Soon, I'm hoping to make a new circomkit feature where people can deploy and verify their circuits using an API call to circuitscan. (like how Foundry and Hardhat verify contracts on Etherscan) This will let people integrate circom deployments into CI builds very easily.

If you have any ideas for circuitscan let me know. It was one of the suggested projects for the EF ZK grants round back in March but I didn't get going until after those applications ended. I'm hoping I can get a grant at some point for this.

Ben

### CODE REVIEW

**Comment by erhant** [comment]
Hey! Circom path as a config makes a lot of sense actually, as you said it allows testing multiple versions, and I think it paves the way for tests using circom forks as well if there are any.

As for circuitscan, it sounds like a really cool project! I would still like to wait a bit before integrating it into Circomkit though, I hope that is understandable 🙏🏻

**Comment by numtel** [comment]
No worries, I'm still at least a week out before I get anything together for that. I've got to make some kind of account system so people can get API keys first.

I hadn't considered it before reading your comment but it makes total sense for it to be a separate package called something like `circomkit-circuitscan-verification` that reads `circomkit.json` and `circuits.json` and is compatible with the same settings. This would be better overall for separation of concerns anyways.

**Comment by erhant** [comment]
I think `circuitscan` itself could be a tool on its own too, right? It could detect the environment, in this case via checking the existence of `circomkit.json`, and piggyback that. I could add that package as an optional dependency to Circomkit as well, which would give it some exposure that way. 

I will be merging this PR now for the circom path, thanks again 🙏🏻

**Comment by erhant** [comment]
For instance, one could add circuitscan as a dependency (without circomkit at all) and verify their circuits there, which would have your tool reach to many more existing projects too!

something like:

```sh
circuitscan verify --r1cs=<path to r1cs> # and such
```

If Circomkit.json exists, it could go for the Circomkit config and read that path from the config.

**Review by erhant — APPROVED** [review]
LGTM

**Pull request merged**
