### PR TITLE
Auto-detect pragma custom_templates for main component instantiation

### PR DESCRIPTION
**Pull request by numtel**
Supercedes #86

### CODE REVIEW

**Comment by erhant** [comment]
Thanks for diving deeper into this along with #86 !
I like this way much more than the other, lets see how it goes and if we end up with many customizations.

One minor request, lets add `usesCustomTemplates` as an optional bool to the circuit config, this way the function signature stays the same & no circuit config out there is affected due to optional param.

**Review by erhant — CHANGES_REQUESTED** [review]
Comment added*

**Comment by erhant** [comment]
heyo, sorry for being late on this a bit, was working on some very buggy stuff elsewhere hahah,

do we need the regex check if user passes `useCustomTemplates` from outside anyways? I think there is no need to do the regex at all, think its better to have the user explicitly state the feature. what do you think?

**Comment by numtel** [comment]
No worries on the delay, you'll have to give me a couple days to look at the c output pr, I'm on my way back to usa after this europe trip atm

My reason for doing the detection instead of requiring the property is the Don't Repeat Yourself principle. It's always going to be in the source file so it's just extra work for developers to have to also specify it again

**Comment by numtel** [comment]
No worries on the delay, you'll have to give me a couple days to look at the c output pr, I'm on my way back to usa after this europe trip atm

My reason for doing the detection instead of requiring the property is the Don't Repeat Yourself principle. It's always going to be in the source file so it's just extra work for developers to have to also specify it again

**Comment by erhant** [comment]
hmm fair point on the DRY!

one minor thing that i want to ask before merge, is regex a must? it will be doing this for ALL files, although a single `contains` could also work as well. I dont think people will have a comment in the middle of `pragma custom_templates;`.

it probably wont matter too much for the performance anyways, but still regex vs contains is a question to be asked i think

P.S. have a nice trip :)

**Comment by erhant** [comment]
- Added a small change so that if `usesCustomTemplate` exists, it does not do the regex check at all.
- Ran a test, some very small minor chores
- Bumped patch version

ready to go!

**Comment by erhant** [comment]
thanks for the PR 🙏🏻

**Comment by erhant** [comment]
Checking out the C tester feature before releasing the new version, it seems really easy to do assuming they share the same interface with Wasm tester, if it turns out to be a greater task I will release this patch anyways!

**Pull request merged**
